# Basic learning content for each course category
# Each topic has sections with title and content

learning_data = {
    "html": {
        "title": "HTML Fundamentals",
        "duration": "2-3 hours",
        "sections": [
            {"title": "What is HTML?", "content": "HTML (HyperText Markup Language) is the backbone of every website. It defines the structure and layout of a web page using a system of tags and attributes. Every web page you see is built with HTML at its core.", "code": "<!DOCTYPE html>\n<html>\n<head>\n  <title>My First Page</title>\n</head>\n<body>\n  <h1>Hello World!</h1>\n</body>\n</html>"},
            {"title": "HTML Elements & Tags", "content": "HTML uses tags like <p>, <h1>, <div>, <span> to define different types of content. Tags usually come in pairs — an opening tag <p> and a closing tag </p>. Some tags like <br> and <img> are self-closing.", "code": "<h1>Main Heading</h1>\n<p>This is a paragraph.</p>\n<a href=\"https://example.com\">Click here</a>\n<img src=\"photo.jpg\" alt=\"A photo\">"},
            {"title": "Headings and Paragraphs", "content": "HTML has 6 heading levels: <h1> (largest, most important) to <h6> (smallest). Use <p> for paragraphs. Headings help structure your document and are important for SEO and accessibility.", "code": "<h1>Page Title</h1>\n<h2>Section Title</h2>\n<h3>Subsection</h3>\n<p>This is a paragraph of text.</p>"},
            {"title": "Links and Images", "content": "The <a> tag creates hyperlinks using the href attribute. The <img> tag embeds images using src for the path and alt for accessibility text. Images are self-closing tags.", "code": "<a href=\"https://google.com\">Visit Google</a>\n<img src=\"logo.png\" alt=\"Company Logo\" width=\"200\">"},
            {"title": "Lists", "content": "HTML supports ordered lists (<ol>) with numbers and unordered lists (<ul>) with bullets. Each list item is wrapped in <li> tags. Lists can be nested inside each other.", "code": "<ul>\n  <li>HTML</li>\n  <li>CSS</li>\n  <li>JavaScript</li>\n</ul>\n\n<ol>\n  <li>First step</li>\n  <li>Second step</li>\n</ol>"},
            {"title": "Forms and Inputs", "content": "Forms collect user input using <form>, <input>, <textarea>, <select>, and <button> elements. The type attribute on <input> determines the kind of data: text, email, password, number, checkbox, radio, etc.", "code": "<form action=\"/submit\" method=\"POST\">\n  <label>Name:</label>\n  <input type=\"text\" name=\"username\">\n  <label>Email:</label>\n  <input type=\"email\" name=\"email\">\n  <button type=\"submit\">Submit</button>\n</form>"},
            {"title": "Semantic HTML5", "content": "HTML5 introduced semantic elements that describe their meaning: <header>, <nav>, <main>, <article>, <section>, <aside>, <footer>. These improve accessibility, SEO, and code readability compared to generic <div> tags.", "code": "<header>\n  <nav>Navigation links</nav>\n</header>\n<main>\n  <article>\n    <h2>Blog Post Title</h2>\n    <p>Content here...</p>\n  </article>\n</main>\n<footer>© 2024 My Site</footer>"},
            {"title": "Tables", "content": "Tables display data in rows and columns using <table>, <tr> (row), <th> (header cell), and <td> (data cell). Use <thead>, <tbody>, and <tfoot> for better structure.", "code": "<table>\n  <thead>\n    <tr><th>Name</th><th>Age</th></tr>\n  </thead>\n  <tbody>\n    <tr><td>Alice</td><td>25</td></tr>\n    <tr><td>Bob</td><td>30</td></tr>\n  </tbody>\n</table>"}
        ]
    },
    "css": {
        "title": "CSS Fundamentals",
        "duration": "3-4 hours",
        "sections": [
            {"title": "What is CSS?", "content": "CSS (Cascading Style Sheets) controls how HTML elements look on screen. It handles colors, fonts, layouts, spacing, animations, and responsiveness. CSS separates content (HTML) from presentation (styling).", "code": "/* External CSS file */\nbody {\n  font-family: Arial, sans-serif;\n  background-color: #f0f0f0;\n  color: #333;\n}"},
            {"title": "Selectors", "content": "CSS selectors target HTML elements to apply styles. Element selectors (p), class selectors (.classname), ID selectors (#idname), and attribute selectors ([type='text']) are the most common. You can combine them for specificity.", "code": "/* Element selector */\np { color: blue; }\n/* Class selector */\n.highlight { background: yellow; }\n/* ID selector */\n#header { font-size: 24px; }\n/* Combined */\ndiv.container p { margin: 10px; }"},
            {"title": "Box Model", "content": "Every HTML element is a rectangular box with four layers: content → padding → border → margin. Understanding the box model is fundamental to controlling layout and spacing in CSS.", "code": ".box {\n  width: 200px;\n  padding: 20px;    /* space inside */\n  border: 2px solid black;\n  margin: 10px;     /* space outside */\n  box-sizing: border-box;\n}"},
            {"title": "Flexbox Layout", "content": "Flexbox is a one-dimensional layout system for arranging items in rows or columns. Set display: flex on a container, then use justify-content, align-items, gap, and flex-wrap to control child element positioning.", "code": ".container {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 20px;\n}\n.item {\n  flex: 1;\n}"},
            {"title": "CSS Grid", "content": "CSS Grid is a two-dimensional layout system for complex page layouts. Define columns and rows with grid-template-columns and grid-template-rows. Place items using grid-column and grid-row.", "code": ".grid {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  grid-gap: 20px;\n}\n.wide-item {\n  grid-column: span 2;\n}"},
            {"title": "Colors and Typography", "content": "CSS supports color names, hex (#FF5733), RGB (rgb(255,87,51)), HSL (hsl(14,100%,60%)), and modern color functions. Typography is controlled with font-family, font-size, font-weight, line-height, and letter-spacing.", "code": "h1 {\n  color: #6C63FF;\n  font-family: 'Inter', sans-serif;\n  font-size: 2.5rem;\n  font-weight: 800;\n  line-height: 1.3;\n  letter-spacing: -0.5px;\n}"},
            {"title": "Responsive Design", "content": "Media queries adapt your layout to different screen sizes. Use @media with min-width or max-width to change styles at breakpoints. Mobile-first design starts with small screens and adds complexity for larger ones.", "code": ".container { padding: 10px; }\n\n@media (min-width: 768px) {\n  .container {\n    padding: 20px;\n    max-width: 720px;\n    margin: 0 auto;\n  }\n}"},
            {"title": "Animations & Transitions", "content": "CSS transitions smoothly animate property changes on hover/interaction. CSS animations use @keyframes for more complex multi-step animations with full control over timing and repetition.", "code": ".button {\n  transition: all 0.3s ease;\n}\n.button:hover {\n  transform: translateY(-3px);\n  box-shadow: 0 10px 20px rgba(0,0,0,0.2);\n}\n\n@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}"}
        ]
    },
    "javascript": {
        "title": "JavaScript Fundamentals",
        "duration": "4-5 hours",
        "sections": [
            {"title": "What is JavaScript?", "content": "JavaScript is the programming language of the web. It makes web pages interactive — handling clicks, validating forms, fetching data, animating elements, and building full applications. It runs in the browser and on servers (Node.js).", "code": "// Your first JavaScript\nconsole.log('Hello, World!');\nalert('Welcome to JavaScript!');"},
            {"title": "Variables and Data Types", "content": "Use let (block-scoped, reassignable), const (block-scoped, constant), or var (function-scoped, legacy) to declare variables. JavaScript has types: string, number, boolean, null, undefined, object, array, and symbol.", "code": "const name = 'Shreya';    // string\nlet age = 22;              // number\nlet isStudent = true;      // boolean\nconst scores = [90, 85];   // array\nconst user = { name, age }; // object"},
            {"title": "Functions", "content": "Functions are reusable blocks of code. Declare with function keyword or arrow syntax (=>). Functions can accept parameters and return values. Arrow functions are shorter and inherit 'this' from their scope.", "code": "// Regular function\nfunction greet(name) {\n  return `Hello, ${name}!`;\n}\n\n// Arrow function\nconst add = (a, b) => a + b;\n\nconsole.log(greet('Shreya')); // Hello, Shreya!\nconsole.log(add(5, 3));       // 8"},
            {"title": "Conditionals & Loops", "content": "if/else statements make decisions. for, while, and for...of loops repeat code. Switch statements handle multiple cases. Ternary operator (condition ? a : b) is a shorthand if/else.", "code": "const score = 85;\nif (score >= 90) {\n  console.log('Excellent!');\n} else if (score >= 70) {\n  console.log('Good job!');\n} else {\n  console.log('Keep trying!');\n}\n\nfor (let i = 0; i < 5; i++) {\n  console.log(i);\n}"},
            {"title": "Arrays & Array Methods", "content": "Arrays store ordered collections. Key methods: push/pop (add/remove end), map (transform each), filter (keep matching), reduce (combine all), find (first match), forEach (loop through).", "code": "const fruits = ['apple', 'banana', 'cherry'];\nfruits.push('date');  // add to end\n\n// Transform each item\nconst upper = fruits.map(f => f.toUpperCase());\n\n// Filter items\nconst long = fruits.filter(f => f.length > 5);\n\n// Find an item\nconst found = fruits.find(f => f === 'banana');"},
            {"title": "Objects", "content": "Objects store data as key-value pairs. Access properties with dot notation (obj.name) or brackets (obj['name']). Destructuring extracts values: const { name, age } = user.", "code": "const user = {\n  name: 'Shreya',\n  age: 22,\n  greet() {\n    return `Hi, I'm ${this.name}`;\n  }\n};\n\nconsole.log(user.name);     // Shreya\nconsole.log(user.greet());  // Hi, I'm Shreya\n\nconst { name, age } = user; // destructuring"},
            {"title": "DOM Manipulation", "content": "The DOM (Document Object Model) represents your HTML as objects JavaScript can interact with. Use document.querySelector() to find elements, then change their content, styles, classes, or listen for events.", "code": "// Select an element\nconst btn = document.querySelector('#myBtn');\n\n// Change content\nbtn.textContent = 'Click Me!';\n\n// Add event listener\nbtn.addEventListener('click', () => {\n  alert('Button clicked!');\n});"},
            {"title": "Async JavaScript", "content": "JavaScript handles async operations with Promises and async/await. fetch() makes HTTP requests. async functions return Promises. await pauses execution until a Promise resolves.", "code": "// Fetch data from API\nasync function getUsers() {\n  try {\n    const response = await fetch('/api/users');\n    const data = await response.json();\n    console.log(data);\n  } catch (error) {\n    console.error('Error:', error);\n  }\n}\n\ngetUsers();"}
        ]
    },
    "python": {
        "title": "Python Fundamentals",
        "duration": "3-4 hours",
        "sections": [
            {"title": "What is Python?", "content": "Python is a versatile, beginner-friendly programming language known for its clean, readable syntax. It's used for web development, data science, AI/ML, automation, scripting, and more.", "code": "# Your first Python program\nprint('Hello, World!')\nname = input('What is your name? ')\nprint(f'Nice to meet you, {name}!')"},
            {"title": "Variables and Data Types", "content": "Python is dynamically typed — you don't declare types. Basic types: str (text), int (whole numbers), float (decimals), bool (True/False), list (ordered collection), dict (key-value pairs), tuple (immutable list), set (unique items).", "code": "name = 'Shreya'        # str\nage = 22               # int\nheight = 5.6           # float\nis_student = True      # bool\nscores = [90, 85, 92]  # list\nuser = {'name': 'Shreya', 'age': 22}  # dict"},
            {"title": "Control Flow", "content": "Python uses if/elif/else for decisions and for/while for loops. Python uses indentation (not braces) to define code blocks. The 'in' keyword checks membership. range() generates number sequences.", "code": "score = 85\nif score >= 90:\n    print('Excellent!')\nelif score >= 70:\n    print('Good job!')\nelse:\n    print('Keep trying!')\n\nfor i in range(5):\n    print(i)\n\nfruits = ['apple', 'banana']\nfor fruit in fruits:\n    print(fruit)"},
            {"title": "Functions", "content": "Define functions with def keyword. Functions can have default parameters, return values, and accept variable arguments (*args, **kwargs). Python supports lambda (anonymous) functions for short expressions.", "code": "def greet(name, greeting='Hello'):\n    return f'{greeting}, {name}!'\n\nprint(greet('Shreya'))          # Hello, Shreya!\nprint(greet('Shreya', 'Hi'))    # Hi, Shreya!\n\n# Lambda function\nsquare = lambda x: x ** 2\nprint(square(5))  # 25"},
            {"title": "Lists and Dictionaries", "content": "Lists are ordered, mutable collections accessed by index. Dictionaries store key-value pairs. List comprehensions provide a concise way to create lists. Both support slicing and iteration.", "code": "# Lists\nnums = [1, 2, 3, 4, 5]\nnums.append(6)\nprint(nums[0])    # 1\nprint(nums[-1])   # 6\n\n# List comprehension\nsquares = [x**2 for x in nums]\n\n# Dictionary\nstudent = {'name': 'Shreya', 'grade': 'A'}\nprint(student['name'])  # Shreya\nstudent['age'] = 22     # add new key"},
            {"title": "String Operations", "content": "Strings are immutable sequences. Use f-strings for formatting. Common methods: split(), join(), strip(), upper(), lower(), replace(), find(). Strings support slicing: text[start:end].", "code": "text = 'Hello, World!'\nprint(text.upper())       # HELLO, WORLD!\nprint(text.split(', '))   # ['Hello', 'World!']\nprint(text[0:5])          # Hello\n\nname = 'Shreya'\nage = 22\nprint(f'{name} is {age} years old')"},
            {"title": "File Handling", "content": "Use open() with 'r' (read), 'w' (write), 'a' (append) modes. The 'with' statement ensures files are properly closed. read(), readline(), readlines() for reading; write() for writing.", "code": "# Write to file\nwith open('data.txt', 'w') as f:\n    f.write('Hello, File!\\n')\n    f.write('Second line')\n\n# Read from file\nwith open('data.txt', 'r') as f:\n    content = f.read()\n    print(content)"},
            {"title": "Exception Handling", "content": "Use try/except to handle errors gracefully. You can catch specific exceptions (ValueError, FileNotFoundError) or all exceptions. 'finally' block runs regardless. 'raise' throws custom exceptions.", "code": "try:\n    num = int(input('Enter a number: '))\n    result = 10 / num\n    print(f'Result: {result}')\nexcept ValueError:\n    print('That is not a valid number!')\nexcept ZeroDivisionError:\n    print('Cannot divide by zero!')\nfinally:\n    print('Done!')"}
        ]
    },
    "java": {
        "title": "Java Fundamentals",
        "duration": "4-5 hours",
        "sections": [
            {"title": "What is Java?", "content": "Java is a powerful, object-oriented programming language that follows 'write once, run anywhere'. It compiles to bytecode that runs on the JVM (Java Virtual Machine), making it platform-independent. Used for enterprise apps, Android, and backend systems.", "code": "public class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}"},
            {"title": "Variables and Data Types", "content": "Java is statically typed — you must declare variable types. Primitive types: int, long, float, double, boolean, char, byte, short. Reference types: String, arrays, objects. Use final for constants.", "code": "int age = 22;\ndouble price = 19.99;\nboolean isActive = true;\nchar grade = 'A';\nString name = \"Shreya\";\nfinal int MAX = 100; // constant"},
            {"title": "Control Flow", "content": "Java uses if/else, switch, for, while, do-while, and enhanced for-each loops. Break exits a loop; continue skips to the next iteration. Switch supports strings and enums.", "code": "int score = 85;\nif (score >= 90) {\n    System.out.println(\"Excellent!\");\n} else if (score >= 70) {\n    System.out.println(\"Good!\");\n}\n\nfor (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}\n\nString[] fruits = {\"apple\", \"banana\"};\nfor (String f : fruits) {\n    System.out.println(f);\n}"},
            {"title": "Classes and Objects", "content": "Everything in Java lives inside a class. A class is a blueprint; an object is an instance. Classes have fields (data) and methods (behavior). Use 'new' to create objects. Constructors initialize objects.", "code": "public class Student {\n    String name;\n    int age;\n\n    Student(String name, int age) {\n        this.name = name;\n        this.age = age;\n    }\n\n    void greet() {\n        System.out.println(\"Hi, I'm \" + name);\n    }\n}\n// Usage: Student s = new Student(\"Shreya\", 22);"},
            {"title": "Inheritance", "content": "Inheritance lets a class inherit fields and methods from another using 'extends'. The child class can override methods. 'super' refers to the parent class. Java supports single inheritance only (but multiple interfaces).", "code": "class Animal {\n    void speak() {\n        System.out.println(\"...\");\n    }\n}\n\nclass Dog extends Animal {\n    @Override\n    void speak() {\n        System.out.println(\"Woof!\");\n    }\n}\n\n// Dog d = new Dog();\n// d.speak(); // Woof!"},
            {"title": "Arrays and Collections", "content": "Arrays have fixed size. ArrayList, LinkedList, HashMap, and HashSet are dynamic collections from java.util. ArrayList is most common — it grows automatically. Use generics for type safety.", "code": "// Array\nint[] nums = {1, 2, 3, 4, 5};\n\n// ArrayList\nimport java.util.ArrayList;\nArrayList<String> list = new ArrayList<>();\nlist.add(\"Hello\");\nlist.add(\"World\");\nSystem.out.println(list.get(0)); // Hello\nSystem.out.println(list.size()); // 2"},
            {"title": "Exception Handling", "content": "Java uses try-catch-finally blocks. Checked exceptions must be caught or declared with 'throws'. Unchecked (runtime) exceptions like NullPointerException don't require handling.", "code": "try {\n    int result = 10 / 0;\n} catch (ArithmeticException e) {\n    System.out.println(\"Error: \" + e.getMessage());\n} finally {\n    System.out.println(\"Always runs\");\n}"},
            {"title": "Interfaces", "content": "Interfaces define a contract of methods that implementing classes must provide. Use 'implements' keyword. A class can implement multiple interfaces. Since Java 8, interfaces can have default methods.", "code": "interface Drawable {\n    void draw();\n    default void info() {\n        System.out.println(\"Drawable object\");\n    }\n}\n\nclass Circle implements Drawable {\n    public void draw() {\n        System.out.println(\"Drawing circle\");\n    }\n}"}
        ]
    },
    "sql": {
        "title": "SQL Fundamentals",
        "duration": "3-4 hours",
        "sections": [
            {"title": "What is SQL?", "content": "SQL (Structured Query Language) is used to communicate with relational databases. You can create, read, update, and delete data (CRUD). Popular databases include MySQL, PostgreSQL, SQLite, and SQL Server.", "code": "-- Create a table\nCREATE TABLE students (\n    id INTEGER PRIMARY KEY,\n    name TEXT NOT NULL,\n    age INTEGER,\n    grade TEXT\n);"},
            {"title": "SELECT — Reading Data", "content": "SELECT retrieves data from tables. Use * for all columns or list specific ones. WHERE filters rows. ORDER BY sorts results. LIMIT restricts the number of rows returned.", "code": "-- Get all students\nSELECT * FROM students;\n\n-- Specific columns with condition\nSELECT name, grade FROM students\nWHERE age > 20\nORDER BY name ASC\nLIMIT 10;"},
            {"title": "INSERT, UPDATE, DELETE", "content": "INSERT adds new rows. UPDATE modifies existing rows (always use WHERE!). DELETE removes rows. Without WHERE on UPDATE/DELETE, ALL rows are affected — be careful!", "code": "-- Insert\nINSERT INTO students (name, age, grade)\nVALUES ('Shreya', 22, 'A');\n\n-- Update\nUPDATE students SET grade = 'A+'\nWHERE name = 'Shreya';\n\n-- Delete\nDELETE FROM students WHERE age < 18;"},
            {"title": "WHERE Clause & Operators", "content": "WHERE filters data using comparison (=, !=, <, >), logical (AND, OR, NOT), pattern (LIKE), range (BETWEEN), and set (IN) operators. NULL checks use IS NULL / IS NOT NULL.", "code": "SELECT * FROM students\nWHERE age BETWEEN 18 AND 25\n  AND grade IN ('A', 'A+')\n  AND name LIKE 'S%'\n  AND email IS NOT NULL;"},
            {"title": "JOINs", "content": "JOINs combine rows from multiple tables based on related columns. INNER JOIN returns matching rows. LEFT JOIN returns all left table rows. FULL OUTER JOIN returns all rows from both tables.", "code": "-- Get students with their courses\nSELECT s.name, c.course_name\nFROM students s\nINNER JOIN enrollments e ON s.id = e.student_id\nINNER JOIN courses c ON e.course_id = c.id;"},
            {"title": "Aggregate Functions", "content": "COUNT, SUM, AVG, MIN, MAX summarize data. GROUP BY groups rows before aggregation. HAVING filters groups (like WHERE but for aggregated data).", "code": "SELECT grade, COUNT(*) as total,\n       AVG(age) as avg_age\nFROM students\nGROUP BY grade\nHAVING COUNT(*) > 5\nORDER BY total DESC;"},
            {"title": "Subqueries", "content": "A subquery is a query inside another query. They can be used in WHERE, FROM, or SELECT clauses. Correlated subqueries reference the outer query and run once per row.", "code": "-- Students above average age\nSELECT name, age FROM students\nWHERE age > (SELECT AVG(age) FROM students);\n\n-- Students with highest grade per class\nSELECT * FROM students s\nWHERE grade = (\n    SELECT MAX(grade) FROM students\n    WHERE class = s.class\n);"},
            {"title": "Indexes and Performance", "content": "Indexes speed up queries by creating a lookup structure (like a book index). Create indexes on frequently queried columns. Too many indexes slow down INSERT/UPDATE operations.", "code": "-- Create an index\nCREATE INDEX idx_student_name\nON students(name);\n\n-- Composite index\nCREATE INDEX idx_grade_age\nON students(grade, age);\n\n-- View query plan\nEXPLAIN QUERY PLAN\nSELECT * FROM students WHERE name = 'Shreya';"}
        ]
    },
    "react": {
        "title": "React Fundamentals",
        "duration": "5-6 hours",
        "sections": [
            {"title": "What is React?", "content": "React is a JavaScript library by Facebook for building user interfaces. It uses a component-based architecture where UI is broken into reusable, independent pieces. React uses a virtual DOM for efficient updates.", "code": "// A simple React component\nimport React from 'react';\n\nfunction App() {\n  return (\n    <div>\n      <h1>Hello, React!</h1>\n    </div>\n  );\n}\n\nexport default App;"},
            {"title": "JSX — JavaScript XML", "content": "JSX lets you write HTML-like syntax in JavaScript. It gets compiled to React.createElement() calls. JSX expressions use {} for JavaScript values. className replaces class; htmlFor replaces for.", "code": "function Welcome({ name }) {\n  const isLoggedIn = true;\n  return (\n    <div className=\"welcome\">\n      <h1>Hello, {name}!</h1>\n      {isLoggedIn ? <p>Welcome back</p> : <p>Please login</p>}\n      <p>2 + 2 = {2 + 2}</p>\n    </div>\n  );\n}"},
            {"title": "Components and Props", "content": "Components are reusable UI building blocks. They accept inputs called 'props' (properties) and return JSX. Props are read-only — a component should never modify its own props. Pass data down from parent to child.", "code": "// Parent passing props\nfunction App() {\n  return <UserCard name=\"Shreya\" role=\"Developer\" />;\n}\n\n// Child receiving props\nfunction UserCard({ name, role }) {\n  return (\n    <div className=\"card\">\n      <h2>{name}</h2>\n      <p>{role}</p>\n    </div>\n  );\n}"},
            {"title": "State with useState", "content": "State is data that changes over time and triggers re-renders. useState hook returns [currentValue, setterFunction]. Never modify state directly — always use the setter. State is local to each component instance.", "code": "import { useState } from 'react';\n\nfunction Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <div>\n      <p>Count: {count}</p>\n      <button onClick={() => setCount(count + 1)}>\n        Increment\n      </button>\n    </div>\n  );\n}"},
            {"title": "useEffect — Side Effects", "content": "useEffect runs code after render: API calls, timers, subscriptions. The dependency array controls when it re-runs: [] = mount only, [dep] = when dep changes, no array = every render. Return a cleanup function for subscriptions.", "code": "import { useState, useEffect } from 'react';\n\nfunction UserList() {\n  const [users, setUsers] = useState([]);\n\n  useEffect(() => {\n    fetch('/api/users')\n      .then(res => res.json())\n      .then(data => setUsers(data));\n  }, []); // runs once on mount\n\n  return (\n    <ul>\n      {users.map(u => <li key={u.id}>{u.name}</li>)}\n    </ul>\n  );\n}"},
            {"title": "Event Handling", "content": "React events use camelCase (onClick, onChange, onSubmit). Pass a function reference, not a call. Use e.preventDefault() to prevent default browser behavior. Arrow functions can pass arguments to handlers.", "code": "function Form() {\n  const [text, setText] = useState('');\n\n  const handleSubmit = (e) => {\n    e.preventDefault();\n    alert(`Submitted: ${text}`);\n  };\n\n  return (\n    <form onSubmit={handleSubmit}>\n      <input\n        value={text}\n        onChange={(e) => setText(e.target.value)}\n      />\n      <button type=\"submit\">Submit</button>\n    </form>\n  );\n}"},
            {"title": "Conditional Rendering", "content": "Show/hide UI based on conditions using ternary operator (condition ? A : B), logical AND (condition && element), or early returns. This is how you build dynamic, interactive interfaces.", "code": "function Dashboard({ isLoggedIn, user }) {\n  if (!isLoggedIn) {\n    return <p>Please log in</p>;\n  }\n\n  return (\n    <div>\n      <h1>Welcome, {user.name}</h1>\n      {user.isAdmin && <button>Admin Panel</button>}\n      {user.score > 90 ? '🏆 Top scorer!' : '📚 Keep going!'}\n    </div>\n  );\n}"},
            {"title": "Lists and Keys", "content": "Render lists using .map() inside JSX. Each list item needs a unique 'key' prop for React's diffing algorithm. Keys should be stable IDs, not array indices (unless the list never changes).", "code": "function TodoList({ items }) {\n  return (\n    <ul>\n      {items.map(item => (\n        <li key={item.id}>\n          <span>{item.text}</span>\n          <span>{item.done ? '✅' : '⬜'}</span>\n        </li>\n      ))}\n    </ul>\n  );\n}"}
        ]
    },
    "csharp": {
        "title": "C# Fundamentals",
        "duration": "4-5 hours",
        "sections": [
            {"title": "What is C#?", "content": "C# (C-Sharp) is a modern, object-oriented language by Microsoft. It powers .NET applications, Unity game development, web APIs, desktop apps, and cloud services. It combines the power of C++ with the simplicity of Java.", "code": "using System;\n\nclass Program {\n    static void Main(string[] args) {\n        Console.WriteLine(\"Hello, C#!\");\n    }\n}"},
            {"title": "Variables and Types", "content": "C# is statically typed. Common types: int, double, float, decimal, bool, char, string. Use 'var' for implicit typing. 'const' for compile-time constants, 'readonly' for runtime constants.", "code": "int age = 22;\ndouble price = 19.99;\nbool isActive = true;\nstring name = \"Shreya\";\nvar score = 95;  // compiler infers int\nconst double PI = 3.14159;"},
            {"title": "Control Flow", "content": "C# supports if/else, switch (including pattern matching), for, foreach, while, and do-while. Switch expressions (C# 8+) provide concise pattern matching. 'break' and 'continue' control loop flow.", "code": "int score = 85;\nstring grade = score switch {\n    >= 90 => \"A\",\n    >= 80 => \"B\",\n    >= 70 => \"C\",\n    _ => \"F\"\n};\n\nint[] nums = {1, 2, 3, 4, 5};\nforeach (int n in nums) {\n    Console.WriteLine(n);\n}"},
            {"title": "Classes and OOP", "content": "C# is fully object-oriented. Classes have properties (auto-implemented with get/set), methods, constructors, and access modifiers (public, private, protected, internal). Use 'new' to create instances.", "code": "public class Student {\n    public string Name { get; set; }\n    public int Age { get; set; }\n\n    public Student(string name, int age) {\n        Name = name;\n        Age = age;\n    }\n\n    public void Greet() {\n        Console.WriteLine($\"Hi, I'm {Name}\");\n    }\n}"},
            {"title": "Inheritance and Interfaces", "content": "Use ':' for inheritance. 'virtual' marks overridable methods; 'override' overrides them. 'abstract' classes cannot be instantiated. Interfaces define contracts. A class can implement multiple interfaces but inherit from only one class.", "code": "interface IDrawable {\n    void Draw();\n}\n\nabstract class Shape {\n    public abstract double Area();\n}\n\nclass Circle : Shape, IDrawable {\n    public double Radius { get; set; }\n    public override double Area() => Math.PI * Radius * Radius;\n    public void Draw() => Console.WriteLine(\"Drawing circle\");\n}"},
            {"title": "Collections and LINQ", "content": "List<T>, Dictionary<TKey,TValue>, HashSet<T>, Queue<T>, Stack<T> are generic collections. LINQ (Language Integrated Query) provides SQL-like querying for any collection using method syntax or query syntax.", "code": "var students = new List<Student>();\nstudents.Add(new Student(\"Shreya\", 22));\n\n// LINQ method syntax\nvar adults = students\n    .Where(s => s.Age >= 18)\n    .OrderBy(s => s.Name)\n    .Select(s => s.Name)\n    .ToList();"},
            {"title": "Async/Await", "content": "async/await enables non-blocking code. Async methods return Task or Task<T>. 'await' pauses execution until the task completes without blocking the thread. Essential for I/O operations like API calls and file access.", "code": "public async Task<string> FetchDataAsync(string url) {\n    using var client = new HttpClient();\n    string result = await client.GetStringAsync(url);\n    return result;\n}\n\n// Usage\nstring data = await FetchDataAsync(\"https://api.example.com\");"},
            {"title": "Exception Handling", "content": "Use try/catch/finally for error handling. Catch specific exceptions before general ones. 'throw' re-throws exceptions. Custom exceptions extend the Exception class. 'using' auto-disposes resources.", "code": "try {\n    int result = int.Parse(\"abc\");\n} catch (FormatException ex) {\n    Console.WriteLine($\"Invalid format: {ex.Message}\");\n} catch (Exception ex) {\n    Console.WriteLine($\"Error: {ex.Message}\");\n} finally {\n    Console.WriteLine(\"Cleanup done\");\n}"}
        ]
    }
}

def get_learning_content(category_id):
    return learning_data.get(category_id, None)
