# All quiz questions organized by category
# 8 Categories × 10 Questions each = 80 total questions

categories = [
    {"id": "html", "name": "HTML", "description": "Master the building blocks of the web", "icon": "🌐", "color": "#E44D26"},
    {"id": "css", "name": "CSS", "description": "Style and design beautiful interfaces", "icon": "🎨", "color": "#264DE4"},
    {"id": "javascript", "name": "JavaScript", "description": "Add interactivity and logic", "icon": "⚡", "color": "#F7DF1E"},
    {"id": "python", "name": "Python", "description": "The versatile programming language", "icon": "🐍", "color": "#3776AB"},
    {"id": "java", "name": "Java", "description": "Enterprise-grade programming", "icon": "☕", "color": "#ED8B00"},
    {"id": "sql", "name": "SQL", "description": "Query and manage databases", "icon": "🗃️", "color": "#00758F"},
    {"id": "react", "name": "React", "description": "Build modern user interfaces", "icon": "⚛️", "color": "#61DAFB"},
    {"id": "csharp", "name": "C#", "description": "Powerful Microsoft ecosystem language", "icon": "🔷", "color": "#68217A"},
]

questions = [
    # ──────────────── HTML (10) ────────────────
    {"id": 1, "category": "html", "text": "What does HTML stand for?",
     "options": ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyper Tool Mouse Language"],
     "correct_answer": "Hyper Text Markup Language"},
    {"id": 2, "category": "html", "text": "Choose the correct HTML element for the largest heading:",
     "options": ["<heading>", "<h1>", "<h6>", "<head>"],
     "correct_answer": "<h1>"},
    {"id": 3, "category": "html", "text": "What is the correct HTML element for inserting a line break?",
     "options": ["<break>", "<lb>", "<br>", "<newline>"],
     "correct_answer": "<br>"},
    {"id": 4, "category": "html", "text": "Which HTML attribute specifies an alternate text for an image?",
     "options": ["title", "src", "alt", "longdesc"],
     "correct_answer": "alt"},
    {"id": 5, "category": "html", "text": "Which element is used to define an unordered list?",
     "options": ["<ol>", "<li>", "<ul>", "<list>"],
     "correct_answer": "<ul>"},
    {"id": 6, "category": "html", "text": "What is the correct HTML for creating a hyperlink?",
     "options": ["<a url='http://example.com'>", "<a href='http://example.com'>", "<link href='http://example.com'>", "<hyperlink>http://example.com</hyperlink>"],
     "correct_answer": "<a href='http://example.com'>"},
    {"id": 7, "category": "html", "text": "Which HTML element is used to define important text?",
     "options": ["<b>", "<strong>", "<important>", "<i>"],
     "correct_answer": "<strong>"},
    {"id": 8, "category": "html", "text": "Which doctype is correct for HTML5?",
     "options": ["<!DOCTYPE html>", "<!DOCTYPE HTML5>", "<!DOCTYPE html5>", "<doctype html>"],
     "correct_answer": "<!DOCTYPE html>"},
    {"id": 9, "category": "html", "text": "Which HTML element is used to specify a footer for a document?",
     "options": ["<bottom>", "<section>", "<footer>", "<end>"],
     "correct_answer": "<footer>"},
    {"id": 10, "category": "html", "text": "Which input type defines a slider control?",
     "options": ["slider", "range", "controls", "slide"],
     "correct_answer": "range"},

    # ──────────────── CSS (10) ────────────────
    {"id": 11, "category": "css", "text": "What does CSS stand for?",
     "options": ["Computer Style Sheets", "Colorful Style Sheets", "Cascading Style Sheets", "Creative Style Sheets"],
     "correct_answer": "Cascading Style Sheets"},
    {"id": 12, "category": "css", "text": "Which property is used to change the background color?",
     "options": ["bgcolor", "color", "background-color", "bg-color"],
     "correct_answer": "background-color"},
    {"id": 13, "category": "css", "text": "Which CSS property controls the text size?",
     "options": ["font-style", "text-size", "font-size", "text-style"],
     "correct_answer": "font-size"},
    {"id": 14, "category": "css", "text": "How do you make text bold in CSS?",
     "options": ["font-style: bold", "text-decoration: bold", "font-weight: bold", "text-style: bold"],
     "correct_answer": "font-weight: bold"},
    {"id": 15, "category": "css", "text": "Which property is used to change the font of an element?",
     "options": ["font-style", "font-weight", "font-family", "font-face"],
     "correct_answer": "font-family"},
    {"id": 16, "category": "css", "text": "How do you select an element with id 'demo' in CSS?",
     "options": [".demo", "#demo", "*demo", "demo"],
     "correct_answer": "#demo"},
    {"id": 17, "category": "css", "text": "How do you add a shadow to elements in CSS3?",
     "options": ["box-shadow", "shadow-effect", "element-shadow", "box-effect"],
     "correct_answer": "box-shadow"},
    {"id": 18, "category": "css", "text": "Which property is used to create space between elements' borders and content?",
     "options": ["margin", "padding", "spacing", "border-spacing"],
     "correct_answer": "padding"},
    {"id": 19, "category": "css", "text": "What is the default value of the position property?",
     "options": ["relative", "fixed", "absolute", "static"],
     "correct_answer": "static"},
    {"id": 20, "category": "css", "text": "Which CSS property is used to make a flex container?",
     "options": ["display: block", "display: flex", "display: grid", "display: inline"],
     "correct_answer": "display: flex"},

    # ──────────────── JavaScript (10) ────────────────
    {"id": 21, "category": "javascript", "text": "Inside which HTML element do we put the JavaScript?",
     "options": ["<js>", "<scripting>", "<script>", "<javascript>"],
     "correct_answer": "<script>"},
    {"id": 22, "category": "javascript", "text": "How do you write 'Hello World' in an alert box?",
     "options": ["alertBox('Hello World')", "msg('Hello World')", "alert('Hello World')", "msgBox('Hello World')"],
     "correct_answer": "alert('Hello World')"},
    {"id": 23, "category": "javascript", "text": "How do you create a function in JavaScript?",
     "options": ["function = myFunction()", "function myFunction()", "function:myFunction()", "create myFunction()"],
     "correct_answer": "function myFunction()"},
    {"id": 24, "category": "javascript", "text": "How does a FOR loop start?",
     "options": ["for (i = 0; i <= 5; i++)", "for (i <= 5; i++)", "for i = 1 to 5", "for (i = 0; i <= 5)"],
     "correct_answer": "for (i = 0; i <= 5; i++)"},
    {"id": 25, "category": "javascript", "text": "What is the correct way to write a JavaScript array?",
     "options": ["var colors = (1:'red', 2:'green')", "var colors = 'red', 'green'", "var colors = ['red', 'green', 'blue']", "var colors = 1 = ('red'), 2 = ('green')"],
     "correct_answer": "var colors = ['red', 'green', 'blue']"},
    {"id": 26, "category": "javascript", "text": "Which operator is used to assign a value to a variable?",
     "options": ["*", "-", "=", "x"],
     "correct_answer": "="},
    {"id": 27, "category": "javascript", "text": "Which event occurs when the user clicks on an HTML element?",
     "options": ["onmouseclick", "onchange", "onclick", "onmouseover"],
     "correct_answer": "onclick"},
    {"id": 28, "category": "javascript", "text": "How do you declare a JavaScript variable?",
     "options": ["variable carName", "var carName", "v carName", "declare carName"],
     "correct_answer": "var carName"},
    {"id": 29, "category": "javascript", "text": "What will typeof null return?",
     "options": ["null", "undefined", "object", "string"],
     "correct_answer": "object"},
    {"id": 30, "category": "javascript", "text": "Which method converts a JSON string to a JavaScript object?",
     "options": ["JSON.parse()", "JSON.stringify()", "JSON.toObject()", "JSON.convert()"],
     "correct_answer": "JSON.parse()"},

    # ──────────────── Python (10) ────────────────
    {"id": 31, "category": "python", "text": "What is the correct file extension for Python files?",
     "options": [".pyth", ".pt", ".py", ".pyt"],
     "correct_answer": ".py"},
    {"id": 32, "category": "python", "text": "How do you insert COMMENTS in Python code?",
     "options": ["// this is a comment", "# this is a comment", "/* this is a comment */", "-- this is a comment"],
     "correct_answer": "# this is a comment"},
    {"id": 33, "category": "python", "text": "Which function is used to output text in Python?",
     "options": ["echo()", "write()", "print()", "output()"],
     "correct_answer": "print()"},
    {"id": 34, "category": "python", "text": "How do you create a variable with the numeric value 5?",
     "options": ["x = 5", "x = int(5)", "Both of the above", "None of the above"],
     "correct_answer": "Both of the above"},
    {"id": 35, "category": "python", "text": "What is the correct way to create a function in Python?",
     "options": ["function myFunc():", "def myFunc():", "create myFunc():", "func myFunc():"],
     "correct_answer": "def myFunc():"},
    {"id": 36, "category": "python", "text": "Which collection is ordered and changeable in Python?",
     "options": ["Set", "Tuple", "List", "Dictionary"],
     "correct_answer": "List"},
    {"id": 37, "category": "python", "text": "What is the output of print(type([]))?",
     "options": ["<class 'tuple'>", "<class 'list'>", "<class 'dict'>", "<class 'set'>"],
     "correct_answer": "<class 'list'>"},
    {"id": 38, "category": "python", "text": "Which keyword is used to handle exceptions in Python?",
     "options": ["catch", "except", "handle", "error"],
     "correct_answer": "except"},
    {"id": 39, "category": "python", "text": "What does the len() function do?",
     "options": ["Returns the length of an object", "Converts to integer", "Rounds a number", "Sorts a list"],
     "correct_answer": "Returns the length of an object"},
    {"id": 40, "category": "python", "text": "Which of these is NOT a Python data type?",
     "options": ["str", "int", "float", "char"],
     "correct_answer": "char"},

    # ──────────────── Java (10) ────────────────
    {"id": 41, "category": "java", "text": "Which keyword is used to define a class in Java?",
     "options": ["define", "struct", "class", "object"],
     "correct_answer": "class"},
    {"id": 42, "category": "java", "text": "What is the correct way to create an object in Java?",
     "options": ["MyClass obj = new MyClass()", "new MyClass obj", "MyClass obj = MyClass()", "create MyClass()"],
     "correct_answer": "MyClass obj = new MyClass()"},
    {"id": 43, "category": "java", "text": "Which method is the entry point of a Java program?",
     "options": ["start()", "run()", "main()", "init()"],
     "correct_answer": "main()"},
    {"id": 44, "category": "java", "text": "Which data type is used to store a single character?",
     "options": ["String", "char", "Character", "txt"],
     "correct_answer": "char"},
    {"id": 45, "category": "java", "text": "What is the size of an int in Java?",
     "options": ["16 bits", "32 bits", "64 bits", "8 bits"],
     "correct_answer": "32 bits"},
    {"id": 46, "category": "java", "text": "Which keyword prevents a class from being inherited?",
     "options": ["static", "private", "final", "abstract"],
     "correct_answer": "final"},
    {"id": 47, "category": "java", "text": "What does JVM stand for?",
     "options": ["Java Very Large Machine", "Java Virtual Machine", "Java Variable Machine", "Java Visual Machine"],
     "correct_answer": "Java Virtual Machine"},
    {"id": 48, "category": "java", "text": "Which of these is a wrapper class for int?",
     "options": ["Int", "INTEGER", "Integer", "number"],
     "correct_answer": "Integer"},
    {"id": 49, "category": "java", "text": "Which keyword is used for inheritance in Java?",
     "options": ["inherits", "implements", "extends", "super"],
     "correct_answer": "extends"},
    {"id": 50, "category": "java", "text": "What does the 'break' statement do?",
     "options": ["Exits the loop", "Skips one iteration", "Continues execution", "Restarts the loop"],
     "correct_answer": "Exits the loop"},

    # ──────────────── SQL (10) ────────────────
    {"id": 51, "category": "sql", "text": "What does SQL stand for?",
     "options": ["Structured Query Language", "Strong Question Language", "Simple Query Language", "Standard Query Logic"],
     "correct_answer": "Structured Query Language"},
    {"id": 52, "category": "sql", "text": "Which SQL statement is used to extract data from a database?",
     "options": ["GET", "OPEN", "EXTRACT", "SELECT"],
     "correct_answer": "SELECT"},
    {"id": 53, "category": "sql", "text": "Which SQL statement is used to update data in a database?",
     "options": ["SAVE", "MODIFY", "UPDATE", "CHANGE"],
     "correct_answer": "UPDATE"},
    {"id": 54, "category": "sql", "text": "Which SQL keyword is used to sort the result-set?",
     "options": ["SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY"],
     "correct_answer": "ORDER BY"},
    {"id": 55, "category": "sql", "text": "Which SQL statement is used to delete data from a database?",
     "options": ["REMOVE", "COLLAPSE", "DELETE", "DROP"],
     "correct_answer": "DELETE"},
    {"id": 56, "category": "sql", "text": "Which SQL clause is used to filter records?",
     "options": ["HAVING", "FILTER", "WHERE", "CONDITION"],
     "correct_answer": "WHERE"},
    {"id": 57, "category": "sql", "text": "Which SQL function returns the number of rows that match a criteria?",
     "options": ["SUM()", "COUNT()", "TOTAL()", "NUMBER()"],
     "correct_answer": "COUNT()"},
    {"id": 58, "category": "sql", "text": "What does the DISTINCT keyword do?",
     "options": ["Sorts data", "Filters null values", "Returns unique values only", "Groups results"],
     "correct_answer": "Returns unique values only"},
    {"id": 59, "category": "sql", "text": "Which JOIN returns all rows when there is a match in either table?",
     "options": ["INNER JOIN", "LEFT JOIN", "FULL OUTER JOIN", "CROSS JOIN"],
     "correct_answer": "FULL OUTER JOIN"},
    {"id": 60, "category": "sql", "text": "What is a PRIMARY KEY?",
     "options": ["The first column in a table", "A unique identifier for each record", "A foreign reference", "An index"],
     "correct_answer": "A unique identifier for each record"},

    # ──────────────── React (10) ────────────────
    {"id": 61, "category": "react", "text": "What is React?",
     "options": ["A server-side framework", "A JavaScript library for building UIs", "A database management tool", "A CSS preprocessor"],
     "correct_answer": "A JavaScript library for building UIs"},
    {"id": 62, "category": "react", "text": "What is JSX?",
     "options": ["A JavaScript compiler", "A syntax extension for JavaScript", "A CSS framework", "A package manager"],
     "correct_answer": "A syntax extension for JavaScript"},
    {"id": 63, "category": "react", "text": "Which hook is used to manage state in functional components?",
     "options": ["useEffect", "useContext", "useState", "useReducer"],
     "correct_answer": "useState"},
    {"id": 64, "category": "react", "text": "What method is used to render a React element into the DOM?",
     "options": ["ReactDOM.render()", "React.mount()", "React.display()", "ReactDOM.create()"],
     "correct_answer": "ReactDOM.render()"},
    {"id": 65, "category": "react", "text": "Which hook runs after every render by default?",
     "options": ["useState", "useEffect", "useMemo", "useCallback"],
     "correct_answer": "useEffect"},
    {"id": 66, "category": "react", "text": "What is a React component?",
     "options": ["A HTML tag", "A reusable piece of UI", "A CSS class", "A JavaScript variable"],
     "correct_answer": "A reusable piece of UI"},
    {"id": 67, "category": "react", "text": "How do you pass data from parent to child component?",
     "options": ["Using state", "Using props", "Using context", "Using refs"],
     "correct_answer": "Using props"},
    {"id": 68, "category": "react", "text": "What is the virtual DOM?",
     "options": ["A real DOM copy", "A lightweight representation of the real DOM", "A browser feature", "A server-side DOM"],
     "correct_answer": "A lightweight representation of the real DOM"},
    {"id": 69, "category": "react", "text": "Which hook is used for performance optimization by memoizing values?",
     "options": ["useState", "useEffect", "useMemo", "useRef"],
     "correct_answer": "useMemo"},
    {"id": 70, "category": "react", "text": "What is the default port for a React development server?",
     "options": ["8080", "5000", "3000", "4200"],
     "correct_answer": "3000"},

    # ──────────────── C# (10) ────────────────
    {"id": 71, "category": "csharp", "text": "What does C# stand for?",
     "options": ["C-Sharp", "C-Hash", "C-Plus", "C-Star"],
     "correct_answer": "C-Sharp"},
    {"id": 72, "category": "csharp", "text": "Which keyword is used to define a namespace in C#?",
     "options": ["package", "namespace", "module", "import"],
     "correct_answer": "namespace"},
    {"id": 73, "category": "csharp", "text": "What is the base class for all classes in C#?",
     "options": ["Base", "Root", "System", "Object"],
     "correct_answer": "Object"},
    {"id": 74, "category": "csharp", "text": "Which keyword is used to indicate that a method can be overridden?",
     "options": ["override", "virtual", "abstract", "static"],
     "correct_answer": "virtual"},
    {"id": 75, "category": "csharp", "text": "What is the correct way to declare a string variable in C#?",
     "options": ["String s = 'hello'", "string s = \"hello\"", "str s = \"hello\"", "var s = hello"],
     "correct_answer": "string s = \"hello\""},
    {"id": 76, "category": "csharp", "text": "Which collection type uses key-value pairs in C#?",
     "options": ["List", "Array", "Dictionary", "Queue"],
     "correct_answer": "Dictionary"},
    {"id": 77, "category": "csharp", "text": "What is LINQ used for in C#?",
     "options": ["Network programming", "Querying data collections", "File management", "UI design"],
     "correct_answer": "Querying data collections"},
    {"id": 78, "category": "csharp", "text": "Which keyword is used to handle exceptions in C#?",
     "options": ["except", "handle", "try-catch", "error"],
     "correct_answer": "try-catch"},
    {"id": 79, "category": "csharp", "text": "What does the 'async' keyword indicate in C#?",
     "options": ["A static method", "An asynchronous method", "A private method", "A constructor"],
     "correct_answer": "An asynchronous method"},
    {"id": 80, "category": "csharp", "text": "Which access modifier makes a member accessible only within its class?",
     "options": ["public", "protected", "internal", "private"],
     "correct_answer": "private"},
]

def get_categories():
    """Return categories with question counts"""
    result = []
    for cat in categories:
        count = len([q for q in questions if q["category"] == cat["id"]])
        result.append({**cat, "questionCount": count})
    return result

def get_questions_by_category(category=None):
    """Return questions (without answers) filtered by category"""
    filtered = questions
    if category:
        filtered = [q for q in questions if q["category"] == category]
    return [{"id": q["id"], "text": q["text"], "options": q["options"], "category": q["category"]} for q in filtered]

def get_question_by_id(q_id):
    """Get a single question by ID (with answer)"""
    for q in questions:
        if q["id"] == q_id:
            return q
    return None
