# All quiz questions organized by category
# 8 Categories x 15 Questions each = 120 total questions (5 easy, 5 medium, 5 hard per category)

categories = [
    {"id": "html", "name": "HTML", "description": "Master the building blocks of the web", "icon": "🌐", "color": "#E44D26",
     "course_info": {
         "overview": "HTML (HyperText Markup Language) is the standard language for creating web pages. It describes the structure of a web page using markup elements like tags and attributes.",
         "what_you_learn": ["Document structure and semantic elements", "Forms and input handling", "Tables, lists, and media embedding", "HTML5 APIs and modern features", "Accessibility best practices"],
         "prerequisites": ["None — perfect for beginners"],
         "estimated_time": "2-3 hours", "skill_level": "Beginner"}},
    {"id": "css", "name": "CSS", "description": "Style and design beautiful interfaces", "icon": "🎨", "color": "#264DE4",
     "course_info": {
         "overview": "CSS (Cascading Style Sheets) controls the visual presentation of web pages. Learn to create stunning layouts, animations, and responsive designs.",
         "what_you_learn": ["Selectors, specificity, and the cascade", "Flexbox and CSS Grid layouts", "Animations and transitions", "Responsive design with media queries", "CSS variables and modern techniques"],
         "prerequisites": ["Basic HTML knowledge"],
         "estimated_time": "3-4 hours", "skill_level": "Beginner"}},
    {"id": "javascript", "name": "JavaScript", "description": "Add interactivity and logic", "icon": "⚡", "color": "#F7DF1E",
     "course_info": {
         "overview": "JavaScript is the programming language of the web. It enables dynamic content, interactive forms, animations, and complex application logic in the browser.",
         "what_you_learn": ["Variables, data types, and operators", "Functions, scope, and closures", "DOM manipulation and events", "Async programming with Promises", "ES6+ modern syntax"],
         "prerequisites": ["Basic HTML & CSS knowledge"],
         "estimated_time": "4-5 hours", "skill_level": "Intermediate"}},
    {"id": "python", "name": "Python", "description": "The versatile programming language", "icon": "🐍", "color": "#3776AB",
     "course_info": {
         "overview": "Python is a versatile, beginner-friendly language used for web development, data science, automation, AI, and more. Known for its clean, readable syntax.",
         "what_you_learn": ["Variables, data types, and control flow", "Functions and modules", "Lists, dictionaries, and comprehensions", "File handling and exceptions", "Object-oriented programming basics"],
         "prerequisites": ["None — great for beginners"],
         "estimated_time": "3-4 hours", "skill_level": "Beginner"}},
    {"id": "java", "name": "Java", "description": "Enterprise-grade programming", "icon": "☕", "color": "#ED8B00",
     "course_info": {
         "overview": "Java is a powerful, object-oriented language used for enterprise apps, Android development, and large-scale systems. It follows the 'write once, run anywhere' philosophy.",
         "what_you_learn": ["OOP concepts: classes, objects, inheritance", "Data types and control structures", "Exception handling and collections", "Interfaces and abstract classes", "JVM architecture basics"],
         "prerequisites": ["Basic programming concepts"],
         "estimated_time": "4-5 hours", "skill_level": "Intermediate"}},
    {"id": "sql", "name": "SQL", "description": "Query and manage databases", "icon": "🗃️", "color": "#00758F",
     "course_info": {
         "overview": "SQL (Structured Query Language) is the standard language for managing and querying relational databases. Essential for any developer working with data.",
         "what_you_learn": ["SELECT, INSERT, UPDATE, DELETE operations", "JOINs and subqueries", "Aggregate functions and GROUP BY", "Indexes and query optimization", "Database design and normalization"],
         "prerequisites": ["None — beginner friendly"],
         "estimated_time": "3-4 hours", "skill_level": "Beginner"}},
    {"id": "react", "name": "React", "description": "Build modern user interfaces", "icon": "⚛️", "color": "#61DAFB",
     "course_info": {
         "overview": "React is a popular JavaScript library for building fast, interactive user interfaces. It uses a component-based architecture and virtual DOM for efficient rendering.",
         "what_you_learn": ["Components, JSX, and props", "State management with hooks", "Side effects with useEffect", "Routing and navigation", "Performance optimization patterns"],
         "prerequisites": ["Solid JavaScript knowledge", "HTML & CSS fundamentals"],
         "estimated_time": "5-6 hours", "skill_level": "Intermediate"}},
    {"id": "csharp", "name": "C#", "description": "Powerful Microsoft ecosystem language", "icon": "🔷", "color": "#68217A",
     "course_info": {
         "overview": "C# is a modern, object-oriented language by Microsoft. It powers .NET applications, game development with Unity, cloud services, and enterprise software.",
         "what_you_learn": ["Syntax, types, and OOP principles", "LINQ and collections", "Async/await patterns", "Exception handling", "Delegates, events, and generics"],
         "prerequisites": ["Basic programming concepts"],
         "estimated_time": "4-5 hours", "skill_level": "Intermediate"}},
]

questions = [
    # ──────────── HTML EASY (5) ────────────
    {"id":1,"category":"html","difficulty":"easy","text":"What does HTML stand for?",
     "options":["Hyper Text Markup Language","Home Tool Markup Language","Hyperlinks and Text Markup Language","Hyper Tool Mouse Language"],
     "correct_answer":"Hyper Text Markup Language",
     "explanation":"HTML stands for Hyper Text Markup Language. It is the standard markup language used to create and structure content on the web."},
    {"id":2,"category":"html","difficulty":"easy","text":"Choose the correct HTML element for the largest heading:",
     "options":["<heading>","<h1>","<h6>","<head>"],
     "correct_answer":"<h1>",
     "explanation":"<h1> defines the largest and most important heading. Headings range from <h1> (largest) to <h6> (smallest)."},
    {"id":3,"category":"html","difficulty":"easy","text":"What is the correct HTML element for inserting a line break?",
     "options":["<break>","<lb>","<br>","<newline>"],
     "correct_answer":"<br>",
     "explanation":"<br> is a self-closing tag that inserts a single line break. It does not require a closing tag."},
    {"id":4,"category":"html","difficulty":"easy","text":"Which HTML attribute specifies an alternate text for an image?",
     "options":["title","src","alt","longdesc"],
     "correct_answer":"alt",
     "explanation":"The 'alt' attribute provides alternative text for an image if it cannot be displayed. It also improves accessibility for screen readers."},
    {"id":5,"category":"html","difficulty":"easy","text":"Which element is used to define an unordered list?",
     "options":["<ol>","<li>","<ul>","<list>"],
     "correct_answer":"<ul>",
     "explanation":"<ul> creates an unordered (bulleted) list. Each item inside is wrapped in <li> tags. <ol> is for ordered (numbered) lists."},
    # ──────────── HTML MEDIUM (5) ────────────
    {"id":6,"category":"html","difficulty":"medium","text":"What is the correct HTML for creating a hyperlink?",
     "options":["<a url='http://example.com'>","<a href='http://example.com'>","<link href='http://example.com'>","<hyperlink>http://example.com</hyperlink>"],
     "correct_answer":"<a href='http://example.com'>",
     "explanation":"The <a> (anchor) tag with the 'href' attribute creates hyperlinks. 'href' stands for Hypertext Reference and specifies the URL."},
    {"id":7,"category":"html","difficulty":"medium","text":"Which HTML element is used to define important text?",
     "options":["<b>","<strong>","<important>","<i>"],
     "correct_answer":"<strong>",
     "explanation":"<strong> indicates that text is of strong importance. While <b> makes text bold visually, <strong> adds semantic meaning for accessibility."},
    {"id":8,"category":"html","difficulty":"medium","text":"Which doctype is correct for HTML5?",
     "options":["<!DOCTYPE html>","<!DOCTYPE HTML5>","<!DOCTYPE html5>","<doctype html>"],
     "correct_answer":"<!DOCTYPE html>",
     "explanation":"<!DOCTYPE html> is the simplified doctype declaration for HTML5. It tells the browser to render the page in standards mode."},
    {"id":9,"category":"html","difficulty":"medium","text":"Which HTML element is used to specify a footer for a document?",
     "options":["<bottom>","<section>","<footer>","<end>"],
     "correct_answer":"<footer>",
     "explanation":"<footer> is a semantic HTML5 element that defines the footer of a document or section, typically containing copyright, links, or author info."},
    {"id":10,"category":"html","difficulty":"medium","text":"Which input type defines a slider control?",
     "options":["slider","range","controls","slide"],
     "correct_answer":"range",
     "explanation":"<input type='range'> creates a slider control that lets users select a value from a given range. You can set min, max, and step attributes."},
    # ──────────── HTML HARD (5) ────────────
    {"id":11,"category":"html","difficulty":"hard","text":"Which HTML5 element is used to draw graphics via JavaScript?",
     "options":["<svg>","<canvas>","<draw>","<graphic>"],
     "correct_answer":"<canvas>",
     "explanation":"<canvas> provides a drawable region in HTML where you can use JavaScript to render graphics, animations, and even games dynamically."},
    {"id":12,"category":"html","difficulty":"hard","text":"What does the 'defer' attribute do on a <script> tag?",
     "options":["Downloads after page loads","Executes script after HTML parsing","Makes script optional","Loads script synchronously"],
     "correct_answer":"Executes script after HTML parsing",
     "explanation":"'defer' tells the browser to download the script in parallel but execute it only after the HTML document has been fully parsed, preventing render blocking."},
    {"id":13,"category":"html","difficulty":"hard","text":"Which attribute makes an input field required before form submission?",
     "options":["validate","necessary","required","mandatory"],
     "correct_answer":"required",
     "explanation":"The 'required' attribute is a boolean attribute that, when present, prevents form submission if the field is empty. It provides built-in client-side validation."},
    {"id":14,"category":"html","difficulty":"hard","text":"What is the purpose of the <template> element?",
     "options":["Defines reusable CSS","Holds client-side content not rendered on load","Creates server templates","Defines page layout"],
     "correct_answer":"Holds client-side content not rendered on load",
     "explanation":"<template> holds HTML content that is not rendered when the page loads. JavaScript can clone and insert this content dynamically at runtime."},
    {"id":15,"category":"html","difficulty":"hard","text":"Which HTML element is used for a self-contained composition like a blog post?",
     "options":["<section>","<div>","<article>","<aside>"],
     "correct_answer":"<article>",
     "explanation":"<article> represents a self-contained composition that could be independently distributed — like a blog post, news article, or forum post."},

    # ──────────── CSS EASY (5) ────────────
    {"id":16,"category":"css","difficulty":"easy","text":"What does CSS stand for?",
     "options":["Computer Style Sheets","Colorful Style Sheets","Cascading Style Sheets","Creative Style Sheets"],
     "correct_answer":"Cascading Style Sheets",
     "explanation":"CSS stands for Cascading Style Sheets. The 'cascading' refers to how styles are applied in order of specificity and source."},
    {"id":17,"category":"css","difficulty":"easy","text":"Which property is used to change the background color?",
     "options":["bgcolor","color","background-color","bg-color"],
     "correct_answer":"background-color",
     "explanation":"'background-color' sets the background color of an element. 'color' changes text color, not the background."},
    {"id":18,"category":"css","difficulty":"easy","text":"Which CSS property controls the text size?",
     "options":["font-style","text-size","font-size","text-style"],
     "correct_answer":"font-size",
     "explanation":"'font-size' sets the size of text. Common units include px, em, rem, and %. 'text-size' is not a valid CSS property."},
    {"id":19,"category":"css","difficulty":"easy","text":"How do you make text bold in CSS?",
     "options":["font-style: bold","text-decoration: bold","font-weight: bold","text-style: bold"],
     "correct_answer":"font-weight: bold",
     "explanation":"'font-weight: bold' makes text bold. You can also use numeric values like 700 for bold or 400 for normal weight."},
    {"id":20,"category":"css","difficulty":"easy","text":"Which property is used to change the font of an element?",
     "options":["font-style","font-weight","font-family","font-face"],
     "correct_answer":"font-family",
     "explanation":"'font-family' specifies the typeface for text. You can list multiple fonts as fallbacks: font-family: 'Arial', sans-serif."},
    # ──────────── CSS MEDIUM (5) ────────────
    {"id":21,"category":"css","difficulty":"medium","text":"How do you select an element with id 'demo' in CSS?",
     "options":[".demo","#demo","*demo","demo"],
     "correct_answer":"#demo",
     "explanation":"The '#' symbol is the ID selector in CSS. IDs must be unique per page. Class selectors use '.' instead."},
    {"id":22,"category":"css","difficulty":"medium","text":"How do you add a shadow to elements in CSS3?",
     "options":["box-shadow","shadow-effect","element-shadow","box-effect"],
     "correct_answer":"box-shadow",
     "explanation":"'box-shadow' adds shadow effects around an element's frame. Syntax: box-shadow: offset-x offset-y blur-radius spread-radius color."},
    {"id":23,"category":"css","difficulty":"medium","text":"Which property creates space between an element's border and content?",
     "options":["margin","padding","spacing","border-spacing"],
     "correct_answer":"padding",
     "explanation":"'padding' creates space inside an element between its content and border. 'margin' creates space outside the border."},
    {"id":24,"category":"css","difficulty":"medium","text":"What is the default value of the position property?",
     "options":["relative","fixed","absolute","static"],
     "correct_answer":"static",
     "explanation":"'static' is the default position. Elements are positioned according to normal document flow. Other values like relative, absolute, fixed change this behavior."},
    {"id":25,"category":"css","difficulty":"medium","text":"Which CSS property is used to make a flex container?",
     "options":["display: block","display: flex","display: grid","display: inline"],
     "correct_answer":"display: flex",
     "explanation":"'display: flex' turns an element into a flex container, enabling powerful one-dimensional layout control for its children."},
    # ──────────── CSS HARD (5) ────────────
    {"id":26,"category":"css","difficulty":"hard","text":"What does 'z-index' control?",
     "options":["Element zoom level","Stacking order of elements","Horizontal position","Element opacity"],
     "correct_answer":"Stacking order of elements",
     "explanation":"'z-index' controls the vertical stacking order of positioned elements. Higher values appear on top. It only works on elements with a position other than static."},
    {"id":27,"category":"css","difficulty":"hard","text":"Which pseudo-class selects every other child element?",
     "options":[":nth-child(2n)",":every-other",":alternate",":second-child"],
     "correct_answer":":nth-child(2n)",
     "explanation":":nth-child(2n) or :nth-child(even) selects every even-numbered child. You can use formulas like 2n+1 for odd, 3n for every third, etc."},
    {"id":28,"category":"css","difficulty":"hard","text":"What is the CSS 'calc()' function used for?",
     "options":["Calculating animations","Performing math calculations for property values","Counting elements","Calculating load time"],
     "correct_answer":"Performing math calculations for property values",
     "explanation":"calc() lets you mix units in calculations, like width: calc(100% - 40px). It supports +, -, *, / and is incredibly useful for responsive layouts."},
    {"id":29,"category":"css","difficulty":"hard","text":"Which CSS property creates a grid layout?",
     "options":["display: table","display: grid","display: columns","display: layout"],
     "correct_answer":"display: grid",
     "explanation":"'display: grid' creates a two-dimensional grid layout system. Combined with grid-template-columns and grid-template-rows, it offers powerful layout control."},
    {"id":30,"category":"css","difficulty":"hard","text":"What does 'will-change' property do?",
     "options":["Detects future DOM changes","Hints browser about upcoming animations for optimization","Changes element state","Triggers change events"],
     "correct_answer":"Hints browser about upcoming animations for optimization",
     "explanation":"'will-change' tells the browser which properties will animate, allowing it to optimize rendering. Use sparingly as overuse can consume memory."},

    # ──────────── JAVASCRIPT EASY (5) ────────────
    {"id":31,"category":"javascript","difficulty":"easy","text":"Inside which HTML element do we put the JavaScript?",
     "options":["<js>","<scripting>","<script>","<javascript>"],
     "correct_answer":"<script>",
     "explanation":"The <script> element is used to embed or reference JavaScript code in an HTML document."},
    {"id":32,"category":"javascript","difficulty":"easy","text":"How do you write 'Hello World' in an alert box?",
     "options":["alertBox('Hello World')","msg('Hello World')","alert('Hello World')","msgBox('Hello World')"],
     "correct_answer":"alert('Hello World')",
     "explanation":"alert() is a built-in browser function that displays a dialog box with the specified message and an OK button."},
    {"id":33,"category":"javascript","difficulty":"easy","text":"How do you create a function in JavaScript?",
     "options":["function = myFunction()","function myFunction()","function:myFunction()","create myFunction()"],
     "correct_answer":"function myFunction()",
     "explanation":"Functions are declared with the 'function' keyword followed by the name and parentheses. You can also use arrow functions: const myFunc = () => {}"},
    {"id":34,"category":"javascript","difficulty":"easy","text":"Which operator is used to assign a value to a variable?",
     "options":["*","-","=","x"],
     "correct_answer":"=",
     "explanation":"The single equals sign (=) is the assignment operator. == checks equality, and === checks strict equality (value and type)."},
    {"id":35,"category":"javascript","difficulty":"easy","text":"How do you declare a JavaScript variable?",
     "options":["variable carName","var carName","v carName","declare carName"],
     "correct_answer":"var carName",
     "explanation":"'var' declares a variable. Modern JavaScript also uses 'let' (block-scoped) and 'const' (constant, block-scoped) for variable declarations."},
    # ──────────── JAVASCRIPT MEDIUM (5) ────────────
    {"id":36,"category":"javascript","difficulty":"medium","text":"How does a FOR loop start?",
     "options":["for (i = 0; i <= 5; i++)","for (i <= 5; i++)","for i = 1 to 5","for (i = 0; i <= 5)"],
     "correct_answer":"for (i = 0; i <= 5; i++)",
     "explanation":"A for loop has three parts: initialization (i=0), condition (i<=5), and increment (i++). The loop runs while the condition is true."},
    {"id":37,"category":"javascript","difficulty":"medium","text":"What is the correct way to write a JavaScript array?",
     "options":["var colors = (1:'red', 2:'green')","var colors = 'red', 'green'","var colors = ['red', 'green', 'blue']","var colors = 1 = ('red'), 2 = ('green')"],
     "correct_answer":"var colors = ['red', 'green', 'blue']",
     "explanation":"Arrays use square brackets [] with comma-separated values. They can hold mixed types and are zero-indexed (first element is at index 0)."},
    {"id":38,"category":"javascript","difficulty":"medium","text":"Which event occurs when the user clicks on an HTML element?",
     "options":["onmouseclick","onchange","onclick","onmouseover"],
     "correct_answer":"onclick",
     "explanation":"'onclick' fires when an element is clicked. 'onmouseover' fires on hover, and 'onchange' fires when an input value changes."},
    {"id":39,"category":"javascript","difficulty":"medium","text":"What will typeof null return?",
     "options":["null","undefined","object","string"],
     "correct_answer":"object",
     "explanation":"typeof null returns 'object' — this is a historical bug in JavaScript from its first implementation that was never fixed for backward compatibility."},
    {"id":40,"category":"javascript","difficulty":"medium","text":"Which method converts a JSON string to a JavaScript object?",
     "options":["JSON.parse()","JSON.stringify()","JSON.toObject()","JSON.convert()"],
     "correct_answer":"JSON.parse()",
     "explanation":"JSON.parse() converts a JSON string into a JavaScript object. JSON.stringify() does the reverse — converts an object to a JSON string."},
    # ──────────── JAVASCRIPT HARD (5) ────────────
    {"id":41,"category":"javascript","difficulty":"hard","text":"What is a closure in JavaScript?",
     "options":["A closed function","A function with access to its outer scope","A terminated process","A sealed object"],
     "correct_answer":"A function with access to its outer scope",
     "explanation":"A closure is a function that remembers and can access variables from its outer (enclosing) scope even after the outer function has finished executing."},
    {"id":42,"category":"javascript","difficulty":"hard","text":"What does the 'this' keyword refer to in an arrow function?",
     "options":["The function itself","The global object always","The enclosing lexical context","The DOM element"],
     "correct_answer":"The enclosing lexical context",
     "explanation":"Arrow functions don't have their own 'this'. They inherit 'this' from the enclosing lexical scope, unlike regular functions which get 'this' based on how they're called."},
    {"id":43,"category":"javascript","difficulty":"hard","text":"What is the event loop responsible for?",
     "options":["Looping through arrays","Managing async callbacks and the call stack","Creating new events","Rendering the DOM"],
     "correct_answer":"Managing async callbacks and the call stack",
     "explanation":"The event loop monitors the call stack and callback queue. When the stack is empty, it moves callbacks from the queue to the stack for execution, enabling non-blocking async behavior."},
    {"id":44,"category":"javascript","difficulty":"hard","text":"What is the difference between '==' and '==='?",
     "options":["No difference","=== compares with type coercion","== compares value and type","=== compares both value and type"],
     "correct_answer":"=== compares both value and type",
     "explanation":"=== (strict equality) checks both value AND type without coercion. == (loose equality) converts types before comparing, so '5' == 5 is true but '5' === 5 is false."},
    {"id":45,"category":"javascript","difficulty":"hard","text":"What does Promise.all() do?",
     "options":["Runs promises sequentially","Resolves when ALL promises resolve, rejects if ANY rejects","Returns the fastest promise","Cancels all promises"],
     "correct_answer":"Resolves when ALL promises resolve, rejects if ANY rejects",
     "explanation":"Promise.all() takes an array of promises and returns a single promise. It resolves with all results when all succeed, or rejects immediately if any single promise rejects."},

    # ──────────── PYTHON EASY (5) ────────────
    {"id":46,"category":"python","difficulty":"easy","text":"What is the correct file extension for Python files?",
     "options":[".pyth",".pt",".py",".pyt"],
     "correct_answer":".py",
     "explanation":"Python files use the .py extension. This tells the operating system and IDE to treat the file as Python source code."},
    {"id":47,"category":"python","difficulty":"easy","text":"How do you insert COMMENTS in Python code?",
     "options":["// this is a comment","# this is a comment","/* this is a comment */","-- this is a comment"],
     "correct_answer":"# this is a comment",
     "explanation":"Python uses # for single-line comments. For multi-line comments, you can use triple quotes (''' or \"\"\") as docstrings."},
    {"id":48,"category":"python","difficulty":"easy","text":"Which function is used to output text in Python?",
     "options":["echo()","write()","print()","output()"],
     "correct_answer":"print()",
     "explanation":"print() outputs text to the console. It can accept multiple arguments and has optional parameters like sep (separator) and end (line ending)."},
    {"id":49,"category":"python","difficulty":"easy","text":"How do you create a variable with the numeric value 5?",
     "options":["x = 5","x = int(5)","Both of the above","None of the above"],
     "correct_answer":"Both of the above",
     "explanation":"Both x = 5 and x = int(5) create a variable with value 5. Python is dynamically typed, so you don't need to declare the type explicitly."},
    {"id":50,"category":"python","difficulty":"easy","text":"What is the correct way to create a function in Python?",
     "options":["function myFunc():","def myFunc():","create myFunc():","func myFunc():"],
     "correct_answer":"def myFunc():",
     "explanation":"'def' keyword defines a function in Python. The function body must be indented. Example: def greet(): print('Hello')"},
    # ──────────── PYTHON MEDIUM (5) ────────────
    {"id":51,"category":"python","difficulty":"medium","text":"Which collection is ordered and changeable in Python?",
     "options":["Set","Tuple","List","Dictionary"],
     "correct_answer":"List",
     "explanation":"Lists are ordered (maintain insertion order) and mutable (changeable). Tuples are ordered but immutable. Sets are unordered and mutable."},
    {"id":52,"category":"python","difficulty":"medium","text":"What is the output of print(type([]))?",
     "options":["<class 'tuple'>","<class 'list'>","<class 'dict'>","<class 'set'>"],
     "correct_answer":"<class 'list'>",
     "explanation":"[] creates an empty list, so type([]) returns <class 'list'>. {} creates a dict, () creates a tuple, and set() creates a set."},
    {"id":53,"category":"python","difficulty":"medium","text":"Which keyword is used to handle exceptions in Python?",
     "options":["catch","except","handle","error"],
     "correct_answer":"except",
     "explanation":"Python uses try/except blocks for exception handling. 'except' catches specific exceptions (or all if no type specified). Java/C# use 'catch' instead."},
    {"id":54,"category":"python","difficulty":"medium","text":"What does the len() function do?",
     "options":["Returns the length of an object","Converts to integer","Rounds a number","Sorts a list"],
     "correct_answer":"Returns the length of an object",
     "explanation":"len() returns the number of items in an object — the length of a string, list, tuple, dictionary, etc."},
    {"id":55,"category":"python","difficulty":"medium","text":"Which of these is NOT a Python data type?",
     "options":["str","int","float","char"],
     "correct_answer":"char",
     "explanation":"Python has no 'char' type. Single characters are simply strings of length 1. Python's basic types include str, int, float, bool, list, dict, tuple, and set."},
    # ──────────── PYTHON HARD (5) ────────────
    {"id":56,"category":"python","difficulty":"hard","text":"What is a list comprehension?",
     "options":["A way to understand lists","A concise way to create lists using a single expression","A list sorting method","A list merging technique"],
     "correct_answer":"A concise way to create lists using a single expression",
     "explanation":"List comprehensions provide a compact syntax: [expr for item in iterable if condition]. Example: [x**2 for x in range(5)] creates [0, 1, 4, 9, 16]."},
    {"id":57,"category":"python","difficulty":"hard","text":"What is a decorator in Python?",
     "options":["A design pattern for UI","A function that modifies another function","A class attribute","A type of comment"],
     "correct_answer":"A function that modifies another function",
     "explanation":"Decorators wrap a function to extend its behavior without modifying it. They use @decorator_name syntax above the function definition."},
    {"id":58,"category":"python","difficulty":"hard","text":"What does *args do in a function definition?",
     "options":["Makes arguments required","Allows passing variable number of positional arguments","Multiplies arguments","Creates argument pointers"],
     "correct_answer":"Allows passing variable number of positional arguments",
     "explanation":"*args collects extra positional arguments into a tuple. Similarly, **kwargs collects extra keyword arguments into a dictionary."},
    {"id":59,"category":"python","difficulty":"hard","text":"What is the Global Interpreter Lock (GIL)?",
     "options":["A file lock mechanism","A mutex that allows only one thread to execute Python bytecode at a time","A security feature","A package manager lock"],
     "correct_answer":"A mutex that allows only one thread to execute Python bytecode at a time",
     "explanation":"The GIL is a mutex in CPython that prevents multiple threads from executing Python bytecode simultaneously, which simplifies memory management but limits true parallelism."},
    {"id":60,"category":"python","difficulty":"hard","text":"What is the difference between a shallow copy and a deep copy?",
     "options":["No difference","Shallow copies nested objects by reference; deep copies recursively","Shallow is faster","Deep copy uses less memory"],
     "correct_answer":"Shallow copies nested objects by reference; deep copies recursively",
     "explanation":"Shallow copy (copy.copy) creates a new object but references nested objects. Deep copy (copy.deepcopy) recursively copies all nested objects, creating fully independent copies."},

    # ──────────── JAVA EASY (5) ────────────
    {"id":61,"category":"java","difficulty":"easy","text":"Which keyword is used to define a class in Java?",
     "options":["define","struct","class","object"],
     "correct_answer":"class",
     "explanation":"The 'class' keyword defines a class in Java. All Java code must be inside a class. Example: public class MyApp { }"},
    {"id":62,"category":"java","difficulty":"easy","text":"What is the correct way to create an object in Java?",
     "options":["MyClass obj = new MyClass()","new MyClass obj","MyClass obj = MyClass()","create MyClass()"],
     "correct_answer":"MyClass obj = new MyClass()",
     "explanation":"Objects are created using the 'new' keyword followed by the constructor. The syntax is: ClassName variableName = new ClassName();"},
    {"id":63,"category":"java","difficulty":"easy","text":"Which method is the entry point of a Java program?",
     "options":["start()","run()","main()","init()"],
     "correct_answer":"main()",
     "explanation":"The main() method (public static void main(String[] args)) is the entry point. The JVM calls this method when the program starts."},
    {"id":64,"category":"java","difficulty":"easy","text":"Which data type is used to store a single character?",
     "options":["String","char","Character","txt"],
     "correct_answer":"char",
     "explanation":"'char' stores a single 16-bit Unicode character. It uses single quotes: char letter = 'A'. String uses double quotes for text."},
    {"id":65,"category":"java","difficulty":"easy","text":"What is the size of an int in Java?",
     "options":["16 bits","32 bits","64 bits","8 bits"],
     "correct_answer":"32 bits",
     "explanation":"int is 32 bits (4 bytes) with range -2^31 to 2^31-1. byte is 8 bits, short is 16 bits, and long is 64 bits."},
    # ──────────── JAVA MEDIUM (5) ────────────
    {"id":66,"category":"java","difficulty":"medium","text":"Which keyword prevents a class from being inherited?",
     "options":["static","private","final","abstract"],
     "correct_answer":"final",
     "explanation":"'final' on a class prevents inheritance. On a method, it prevents overriding. On a variable, it makes it constant (can't be reassigned)."},
    {"id":67,"category":"java","difficulty":"medium","text":"What does JVM stand for?",
     "options":["Java Very Large Machine","Java Virtual Machine","Java Variable Machine","Java Visual Machine"],
     "correct_answer":"Java Virtual Machine",
     "explanation":"JVM (Java Virtual Machine) executes Java bytecode. It provides platform independence — write once, run anywhere — by abstracting the underlying OS."},
    {"id":68,"category":"java","difficulty":"medium","text":"Which of these is a wrapper class for int?",
     "options":["Int","INTEGER","Integer","number"],
     "correct_answer":"Integer",
     "explanation":"Integer is the wrapper class for primitive int. Wrapper classes allow primitives to be used as objects, enabling features like collections and null values."},
    {"id":69,"category":"java","difficulty":"medium","text":"Which keyword is used for inheritance in Java?",
     "options":["inherits","implements","extends","super"],
     "correct_answer":"extends",
     "explanation":"'extends' creates class inheritance. 'implements' is used for interfaces. 'super' refers to the parent class but doesn't declare inheritance."},
    {"id":70,"category":"java","difficulty":"medium","text":"What does the 'break' statement do?",
     "options":["Exits the loop","Skips one iteration","Continues execution","Restarts the loop"],
     "correct_answer":"Exits the loop",
     "explanation":"'break' immediately exits the nearest enclosing loop or switch. 'continue' skips the current iteration and moves to the next one."},
    # ──────────── JAVA HARD (5) ────────────
    {"id":71,"category":"java","difficulty":"hard","text":"What is the difference between an abstract class and an interface?",
     "options":["No difference","Abstract classes can have constructors and state; interfaces cannot","Interfaces are faster","Abstract classes support multiple inheritance"],
     "correct_answer":"Abstract classes can have constructors and state; interfaces cannot",
     "explanation":"Abstract classes can have instance variables, constructors, and both abstract and concrete methods. Interfaces (pre-Java 8) only have abstract methods and constants. Java supports multiple interface implementation but single class inheritance."},
    {"id":72,"category":"java","difficulty":"hard","text":"What is autoboxing in Java?",
     "options":["Automatic packaging","Automatic conversion between primitives and wrapper classes","Auto-compiling","Automatic memory allocation"],
     "correct_answer":"Automatic conversion between primitives and wrapper classes",
     "explanation":"Autoboxing automatically converts primitives to wrapper objects (int → Integer) and vice versa (unboxing). This enables seamless use of primitives in collections."},
    {"id":73,"category":"java","difficulty":"hard","text":"Which collection does NOT allow duplicate elements?",
     "options":["ArrayList","LinkedList","HashSet","Vector"],
     "correct_answer":"HashSet",
     "explanation":"HashSet implements the Set interface which guarantees uniqueness — no duplicate elements. ArrayList, LinkedList, and Vector all allow duplicates."},
    {"id":74,"category":"java","difficulty":"hard","text":"What is the purpose of the 'volatile' keyword?",
     "options":["Makes variable constant","Ensures visibility of changes across threads","Speeds up access","Prevents garbage collection"],
     "correct_answer":"Ensures visibility of changes across threads",
     "explanation":"'volatile' ensures that changes to a variable are immediately visible to all threads. It prevents thread-local caching and guarantees read/write ordering."},
    {"id":75,"category":"java","difficulty":"hard","text":"What design pattern does Java's Iterator implement?",
     "options":["Singleton","Observer","Iterator/Behavioral","Factory"],
     "correct_answer":"Iterator/Behavioral",
     "explanation":"Iterator is a behavioral design pattern that provides a way to access elements of a collection sequentially without exposing its underlying representation."},

    # ──────────── SQL EASY (5) ────────────
    {"id":76,"category":"sql","difficulty":"easy","text":"What does SQL stand for?",
     "options":["Structured Query Language","Strong Question Language","Simple Query Language","Standard Query Logic"],
     "correct_answer":"Structured Query Language",
     "explanation":"SQL stands for Structured Query Language. It is the standard language for managing and manipulating relational databases."},
    {"id":77,"category":"sql","difficulty":"easy","text":"Which SQL statement is used to extract data from a database?",
     "options":["GET","OPEN","EXTRACT","SELECT"],
     "correct_answer":"SELECT",
     "explanation":"SELECT retrieves data from one or more tables. Basic syntax: SELECT column1, column2 FROM table_name WHERE condition."},
    {"id":78,"category":"sql","difficulty":"easy","text":"Which SQL statement is used to update data in a database?",
     "options":["SAVE","MODIFY","UPDATE","CHANGE"],
     "correct_answer":"UPDATE",
     "explanation":"UPDATE modifies existing records. Syntax: UPDATE table SET column=value WHERE condition. Always use WHERE to avoid updating all rows."},
    {"id":79,"category":"sql","difficulty":"easy","text":"Which SQL keyword is used to sort the result-set?",
     "options":["SORT BY","ORDER BY","GROUP BY","ARRANGE BY"],
     "correct_answer":"ORDER BY",
     "explanation":"ORDER BY sorts results in ascending (ASC, default) or descending (DESC) order. GROUP BY groups rows with the same values, not sorting."},
    {"id":80,"category":"sql","difficulty":"easy","text":"Which SQL statement is used to delete data from a database?",
     "options":["REMOVE","COLLAPSE","DELETE","DROP"],
     "correct_answer":"DELETE",
     "explanation":"DELETE removes rows from a table. DROP removes the entire table structure. Always use WHERE with DELETE to target specific rows."},
    # ──────────── SQL MEDIUM (5) ────────────
    {"id":81,"category":"sql","difficulty":"medium","text":"Which SQL clause is used to filter records?",
     "options":["HAVING","FILTER","WHERE","CONDITION"],
     "correct_answer":"WHERE",
     "explanation":"WHERE filters individual rows before grouping. HAVING filters groups after GROUP BY. There is no FILTER or CONDITION clause in standard SQL."},
    {"id":82,"category":"sql","difficulty":"medium","text":"Which SQL function returns the number of rows that match a criteria?",
     "options":["SUM()","COUNT()","TOTAL()","NUMBER()"],
     "correct_answer":"COUNT()",
     "explanation":"COUNT() returns the number of rows matching a condition. COUNT(*) counts all rows; COUNT(column) counts non-NULL values in that column."},
    {"id":83,"category":"sql","difficulty":"medium","text":"What does the DISTINCT keyword do?",
     "options":["Sorts data","Filters null values","Returns unique values only","Groups results"],
     "correct_answer":"Returns unique values only",
     "explanation":"DISTINCT eliminates duplicate rows from the result set. SELECT DISTINCT city FROM customers returns each city name only once."},
    {"id":84,"category":"sql","difficulty":"medium","text":"Which JOIN returns all rows when there is a match in either table?",
     "options":["INNER JOIN","LEFT JOIN","FULL OUTER JOIN","CROSS JOIN"],
     "correct_answer":"FULL OUTER JOIN",
     "explanation":"FULL OUTER JOIN returns all rows from both tables, matching where possible and filling NULLs where there's no match. INNER JOIN returns only matching rows."},
    {"id":85,"category":"sql","difficulty":"medium","text":"What is a PRIMARY KEY?",
     "options":["The first column in a table","A unique identifier for each record","A foreign reference","An index"],
     "correct_answer":"A unique identifier for each record",
     "explanation":"A PRIMARY KEY uniquely identifies each row in a table. It must contain unique, non-NULL values. A table can only have one primary key."},
    # ──────────── SQL HARD (5) ────────────
    {"id":86,"category":"sql","difficulty":"hard","text":"What is database normalization?",
     "options":["Making database faster","Organizing data to reduce redundancy and dependency","Backing up data","Encrypting data"],
     "correct_answer":"Organizing data to reduce redundancy and dependency",
     "explanation":"Normalization structures a database to minimize data duplication. It involves splitting tables and defining relationships using normal forms (1NF, 2NF, 3NF, etc.)."},
    {"id":87,"category":"sql","difficulty":"hard","text":"What is a correlated subquery?",
     "options":["A subquery that runs once","A subquery that references columns from the outer query","A stored procedure","A query with JOINs"],
     "correct_answer":"A subquery that references columns from the outer query",
     "explanation":"A correlated subquery references the outer query's columns and executes once for each row of the outer query, unlike a regular subquery which runs once independently."},
    {"id":88,"category":"sql","difficulty":"hard","text":"What is an SQL injection?",
     "options":["Adding data to a database","A security vulnerability where malicious SQL is inserted via input","A type of JOIN","A database optimization technique"],
     "correct_answer":"A security vulnerability where malicious SQL is inserted via input",
     "explanation":"SQL injection occurs when user input is directly embedded in SQL queries without sanitization, allowing attackers to manipulate queries. Prevent it using parameterized queries."},
    {"id":89,"category":"sql","difficulty":"hard","text":"What does the COALESCE function do?",
     "options":["Combines tables","Returns the first non-NULL value from a list","Counts rows","Merges columns"],
     "correct_answer":"Returns the first non-NULL value from a list",
     "explanation":"COALESCE takes multiple arguments and returns the first one that is not NULL. Example: COALESCE(phone, email, 'N/A') returns the first available contact method."},
    {"id":90,"category":"sql","difficulty":"hard","text":"What is a database transaction?",
     "options":["A payment record","A unit of work that is atomic, consistent, isolated, and durable (ACID)","A query log","A backup process"],
     "correct_answer":"A unit of work that is atomic, consistent, isolated, and durable (ACID)",
     "explanation":"Transactions group operations so they all succeed or all fail (atomic). ACID properties ensure data integrity: Atomicity, Consistency, Isolation, Durability."},

    # ──────────── REACT EASY (5) ────────────
    {"id":91,"category":"react","difficulty":"easy","text":"What is React?",
     "options":["A server-side framework","A JavaScript library for building UIs","A database management tool","A CSS preprocessor"],
     "correct_answer":"A JavaScript library for building UIs",
     "explanation":"React is an open-source JavaScript library created by Facebook for building fast, interactive user interfaces using a component-based architecture."},
    {"id":92,"category":"react","difficulty":"easy","text":"What is JSX?",
     "options":["A JavaScript compiler","A syntax extension for JavaScript","A CSS framework","A package manager"],
     "correct_answer":"A syntax extension for JavaScript",
     "explanation":"JSX lets you write HTML-like syntax in JavaScript. It gets compiled to React.createElement() calls. It makes component templates more readable."},
    {"id":93,"category":"react","difficulty":"easy","text":"Which hook is used to manage state in functional components?",
     "options":["useEffect","useContext","useState","useReducer"],
     "correct_answer":"useState",
     "explanation":"useState returns a state variable and a setter function. Example: const [count, setCount] = useState(0). It triggers re-renders when state changes."},
    {"id":94,"category":"react","difficulty":"easy","text":"What is a React component?",
     "options":["A HTML tag","A reusable piece of UI","A CSS class","A JavaScript variable"],
     "correct_answer":"A reusable piece of UI",
     "explanation":"Components are independent, reusable pieces of UI. They can be functions or classes that accept props and return JSX describing what should appear on screen."},
    {"id":95,"category":"react","difficulty":"easy","text":"How do you pass data from parent to child component?",
     "options":["Using state","Using props","Using context","Using refs"],
     "correct_answer":"Using props",
     "explanation":"Props (properties) are passed from parent to child like HTML attributes: <Child name='John' />. Props are read-only in the child component."},
    # ──────────── REACT MEDIUM (5) ────────────
    {"id":96,"category":"react","difficulty":"medium","text":"What method is used to render a React element into the DOM?",
     "options":["ReactDOM.render()","React.mount()","React.display()","ReactDOM.create()"],
     "correct_answer":"ReactDOM.render()",
     "explanation":"ReactDOM.render() mounts a React element into a DOM node. In React 18+, createRoot().render() is the modern replacement."},
    {"id":97,"category":"react","difficulty":"medium","text":"Which hook runs after every render by default?",
     "options":["useState","useEffect","useMemo","useCallback"],
     "correct_answer":"useEffect",
     "explanation":"useEffect runs after every render by default. Pass a dependency array to control when it re-runs. An empty array [] means it runs only on mount."},
    {"id":98,"category":"react","difficulty":"medium","text":"What is the virtual DOM?",
     "options":["A real DOM copy","A lightweight representation of the real DOM","A browser feature","A server-side DOM"],
     "correct_answer":"A lightweight representation of the real DOM",
     "explanation":"The virtual DOM is an in-memory JavaScript representation of the real DOM. React compares it with the previous version (diffing) and updates only changed parts efficiently."},
    {"id":99,"category":"react","difficulty":"medium","text":"What is the default port for a React development server?",
     "options":["8080","5000","3000","4200"],
     "correct_answer":"3000",
     "explanation":"Create React App's dev server defaults to port 3000. Vite uses 5173. If the port is busy, it will suggest the next available port."},
    {"id":100,"category":"react","difficulty":"medium","text":"Which hook is used for performance optimization by memoizing values?",
     "options":["useState","useEffect","useMemo","useRef"],
     "correct_answer":"useMemo",
     "explanation":"useMemo memoizes expensive computed values, recalculating only when dependencies change. useCallback similarly memoizes function references."},
    # ──────────── REACT HARD (5) ────────────
    {"id":101,"category":"react","difficulty":"hard","text":"What is React's reconciliation algorithm?",
     "options":["A sorting algorithm","The process of comparing virtual DOM trees to update the real DOM","A state management technique","A routing algorithm"],
     "correct_answer":"The process of comparing virtual DOM trees to update the real DOM",
     "explanation":"Reconciliation is React's diffing algorithm that compares the new virtual DOM with the previous one and calculates the minimal set of changes needed to update the real DOM."},
    {"id":102,"category":"react","difficulty":"hard","text":"What is the purpose of React.memo()?",
     "options":["Memoizes state","Prevents unnecessary re-renders of functional components","Stores data in memory","Creates memos/notes"],
     "correct_answer":"Prevents unnecessary re-renders of functional components",
     "explanation":"React.memo() is a higher-order component that skips re-rendering if props haven't changed (shallow comparison). It's the functional equivalent of PureComponent."},
    {"id":103,"category":"react","difficulty":"hard","text":"What problem does useCallback solve?",
     "options":["Handling errors","Preventing function recreation on every render","Making API calls","Managing routing"],
     "correct_answer":"Preventing function recreation on every render",
     "explanation":"useCallback returns a memoized version of a callback that only changes when dependencies change. This prevents unnecessary re-renders of child components receiving the callback as a prop."},
    {"id":104,"category":"react","difficulty":"hard","text":"What is a React Portal?",
     "options":["A routing mechanism","A way to render children into a DOM node outside the parent hierarchy","A state container","A testing tool"],
     "correct_answer":"A way to render children into a DOM node outside the parent hierarchy",
     "explanation":"Portals let you render children outside the parent DOM tree (e.g., modals, tooltips). Created with ReactDOM.createPortal(child, container). Events still bubble through the React tree."},
    {"id":105,"category":"react","difficulty":"hard","text":"What is the purpose of the key prop in lists?",
     "options":["Styling elements","Helping React identify which items changed, were added, or removed","Sorting elements","Encrypting data"],
     "correct_answer":"Helping React identify which items changed, were added, or removed",
     "explanation":"Keys give elements a stable identity across re-renders. React uses keys to efficiently update lists by matching old and new elements. Always use unique, stable IDs — avoid array indices."},

    # ──────────── C# EASY (5) ────────────
    {"id":106,"category":"csharp","difficulty":"easy","text":"What does C# stand for?",
     "options":["C-Sharp","C-Hash","C-Plus","C-Star"],
     "correct_answer":"C-Sharp",
     "explanation":"C# is pronounced 'C-Sharp.' The '#' symbol is inspired by the musical sharp notation, indicating the language is an evolution of C/C++."},
    {"id":107,"category":"csharp","difficulty":"easy","text":"Which keyword is used to define a namespace in C#?",
     "options":["package","namespace","module","import"],
     "correct_answer":"namespace",
     "explanation":"'namespace' organizes code into logical groups and prevents naming conflicts. Java uses 'package' for a similar purpose."},
    {"id":108,"category":"csharp","difficulty":"easy","text":"What is the base class for all classes in C#?",
     "options":["Base","Root","System","Object"],
     "correct_answer":"Object",
     "explanation":"System.Object is the ultimate base class of all classes in C#. Every class implicitly inherits from Object, which provides methods like ToString(), Equals(), and GetHashCode()."},
    {"id":109,"category":"csharp","difficulty":"easy","text":"What is the correct way to declare a string variable in C#?",
     "options":["String s = 'hello'","string s = \"hello\"","str s = \"hello\"","var s = hello"],
     "correct_answer":"string s = \"hello\"",
     "explanation":"C# uses double quotes for strings. 'string' (lowercase) is an alias for System.String. Single quotes are for char type only."},
    {"id":110,"category":"csharp","difficulty":"easy","text":"Which keyword is used to handle exceptions in C#?",
     "options":["except","handle","try-catch","error"],
     "correct_answer":"try-catch",
     "explanation":"C# uses try-catch blocks for exception handling, with an optional 'finally' block for cleanup code that always runs."},
    # ──────────── C# MEDIUM (5) ────────────
    {"id":111,"category":"csharp","difficulty":"medium","text":"Which keyword indicates that a method can be overridden?",
     "options":["override","virtual","abstract","static"],
     "correct_answer":"virtual",
     "explanation":"'virtual' marks a method as overridable in derived classes. 'override' is used in the child class to actually override it. 'abstract' forces implementation in child classes."},
    {"id":112,"category":"csharp","difficulty":"medium","text":"Which collection type uses key-value pairs in C#?",
     "options":["List","Array","Dictionary","Queue"],
     "correct_answer":"Dictionary",
     "explanation":"Dictionary<TKey, TValue> stores key-value pairs with O(1) lookup time. Example: var dict = new Dictionary<string, int>(); dict[\"age\"] = 25;"},
    {"id":113,"category":"csharp","difficulty":"medium","text":"What is LINQ used for in C#?",
     "options":["Network programming","Querying data collections","File management","UI design"],
     "correct_answer":"Querying data collections",
     "explanation":"LINQ (Language Integrated Query) provides a uniform syntax to query arrays, lists, databases, and XML. Example: var result = list.Where(x => x > 5).OrderBy(x => x);"},
    {"id":114,"category":"csharp","difficulty":"medium","text":"What does the 'async' keyword indicate in C#?",
     "options":["A static method","An asynchronous method","A private method","A constructor"],
     "correct_answer":"An asynchronous method",
     "explanation":"'async' marks a method as asynchronous, allowing the use of 'await' inside it. The method typically returns Task or Task<T> and enables non-blocking operations."},
    {"id":115,"category":"csharp","difficulty":"medium","text":"Which access modifier makes a member accessible only within its class?",
     "options":["public","protected","internal","private"],
     "correct_answer":"private",
     "explanation":"'private' restricts access to the containing class only. 'protected' allows child classes. 'internal' allows same assembly. 'public' allows access from anywhere."},
    # ──────────── C# HARD (5) ────────────
    {"id":116,"category":"csharp","difficulty":"hard","text":"What are delegates in C#?",
     "options":["Team members","Type-safe function pointers","Database connections","UI components"],
     "correct_answer":"Type-safe function pointers",
     "explanation":"Delegates are type-safe references to methods. They define a method signature and can point to any method matching that signature. They're the foundation of events and callbacks in C#."},
    {"id":117,"category":"csharp","difficulty":"hard","text":"What is the difference between 'ref' and 'out' parameters?",
     "options":["No difference","ref must be initialized before passing; out must be assigned inside the method","ref is faster","out is read-only"],
     "correct_answer":"ref must be initialized before passing; out must be assigned inside the method",
     "explanation":"Both pass by reference, but 'ref' requires the variable to be initialized before the call, while 'out' requires the method to assign a value before returning."},
    {"id":118,"category":"csharp","difficulty":"hard","text":"What is the purpose of the 'yield' keyword?",
     "options":["Pauses thread execution","Returns elements one at a time from an iterator","Gives up CPU time","Yields control to OS"],
     "correct_answer":"Returns elements one at a time from an iterator",
     "explanation":"'yield return' creates an iterator that returns elements lazily (one at a time). This enables deferred execution and memory-efficient processing of large sequences."},
    {"id":119,"category":"csharp","difficulty":"hard","text":"What is dependency injection?",
     "options":["Injecting code at runtime","A design pattern where dependencies are provided rather than created internally","A security vulnerability","A compilation step"],
     "correct_answer":"A design pattern where dependencies are provided rather than created internally",
     "explanation":"Dependency Injection (DI) provides objects their dependencies from outside rather than creating them internally. This promotes loose coupling, testability, and maintainability."},
    {"id":120,"category":"csharp","difficulty":"hard","text":"What is the difference between IEnumerable and IQueryable?",
     "options":["No difference","IEnumerable processes in-memory; IQueryable translates to database queries","IQueryable is faster always","IEnumerable is for databases"],
     "correct_answer":"IEnumerable processes in-memory; IQueryable translates to database queries",
     "explanation":"IEnumerable executes queries in memory (client-side). IQueryable builds expression trees that can be translated to SQL, enabling server-side filtering — much more efficient for database queries."},
]

def get_categories():
    result = []
    for cat in categories:
        cat_questions = [q for q in questions if q["category"] == cat["id"]]
        easy_count = len([q for q in cat_questions if q["difficulty"] == "easy"])
        medium_count = len([q for q in cat_questions if q["difficulty"] == "medium"])
        hard_count = len([q for q in cat_questions if q["difficulty"] == "hard"])
        result.append({**cat, "questionCount": len(cat_questions),
                       "easyCt": easy_count, "mediumCt": medium_count, "hardCt": hard_count})
    return result

def get_questions_by_category(category=None, difficulty=None):
    filtered = questions
    if category:
        filtered = [q for q in filtered if q["category"] == category]
    if difficulty:
        filtered = [q for q in filtered if q["difficulty"] == difficulty]
    return [{"id": q["id"], "text": q["text"], "options": q["options"],
             "category": q["category"], "difficulty": q["difficulty"]} for q in filtered]

def get_question_by_id(q_id):
    for q in questions:
        if q["id"] == q_id:
            return q
    return None

def get_course_info(category_id):
    for cat in categories:
        if cat["id"] == category_id:
            cat_questions = [q for q in questions if q["category"] == category_id]
            return {
                **cat,
                "questionCount": len(cat_questions),
                "easyCt": len([q for q in cat_questions if q["difficulty"] == "easy"]),
                "mediumCt": len([q for q in cat_questions if q["difficulty"] == "medium"]),
                "hardCt": len([q for q in cat_questions if q["difficulty"] == "hard"]),
            }
    return None
